export interface Agent {
    id: number,
    name: string,
    agentId: string,
    phone: string,
    Address: string,
     address: string,
    City: string,
    State: string,
    Zip_code: number,
    Latitude: string,
    Longitude: string,
    slug: string,
    person_name: string,
    person_photo: string,
    person_email: string,
    description: string,
    insurance_coverage: string,
    ad_banner: string,
    ad_banner_title: string,
    ad_banner_subtitle: string,
    ad_banner_button: string,
    ad_banner_button_url: string,
    ad_banner2: string,
    ad_banner_title2: string,
    ad_banner_subtitle2: string,
    ad_banner_button_text2: string,
     ad_banner_button_url2: string,
     ad_banner3: string,
     ad_banner_title3: string,
      ad_banner_subtitle3: string,
      ad_banner_button_text3: string,
      ad_banner_button_url3: string,

}
